export enum ValidationSeverity {
  ERROR = 'error',
  FATAL = 'fatal',
  WARNING = 'warning',
}

export const HIGH_CONSUMPTION_THRESHOLD = 999999;

export enum ValidationCode {
  INVALID_CONSUMPTION_FORMAT = 'INVALID_CONSUMPTION_FORMAT',
  NEGATIVE_CONSUMPTION = 'NEGATIVE_CONSUMPTION',
  SUSPICIOUS_CONSUMPTION_HIGH = 'SUSPICIOUS_CONSUMPTION_HIGH',
  INVALID_DATE = 'INVALID_DATE',
  MISSING_INTERVAL_LENGTH = 'MISSING_INTERVAL_LENGTH',
  MISSING_INTERVAL_FIELDS = 'MISSING_INTERVAL_FIELDS',
  MISSING_NMI_FIELDS = 'MISSING_NMI_FIELDS',
  INVALID_INTERVAL_LENGTH = 'INVALID_INTERVAL_LENGTH',
  INVALID_VERSION = 'INVALID_VERSION',
  MISSING_HEADER_FIELDS = 'MISSING_HEADER_FIELDS',
}
